version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Jhon.123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql  # Persistencia de datos
      - ./DBSetup.sql:/docker-entrypoint-initdb.d/DBSetup.sql
    networks:
      - app-network
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=StoreSample;User Id=sa;Password=Jhon.123;TrustServerCertificate=True;"
    networks:
      - app-network

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: mssql-tools
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - sqlserver
    volumes:
      - ./DBSetup.sql:/usr/src/app/DBSetup.sql
      - ./init-db.sh:/usr/src/app/init-db.sh
    command: ["sh", "/usr/src/app/init-db.sh"]

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver_data:
